name: Open API

on:
  push:
    branches:
      - main

jobs:
  your_job_name:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run server
      run: node server.js
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
